### ISSUE TITLE
client is zoomed (f) in addr, offset

### ISSUE THREAD

**Issue by iceisfun** [hectorgimenez/d2go#8]
PatternBaseAddress = Scan(00 00 06 00 00 00 ?? ?? ?? ?? ?? ?? ?? 43 ?? ?? ?? ?? ?? ?? ?? ?? 00 00 00 00 01 00 00 00 00 00 00 00 00 00 80 3F)
Zoom : uint64(PatternBaseAddress + 0x30)

Pattern occurs outside the base module

Zoomed In : 0x003f0000003f00
Zooming in (motion) > 0x003f0000003000 && != 0x003f0000003f00
Zoomed Out : 0x00
Zooming out (motion) > 0 && < 0xffff

Example Data
```
// ----[ dumping address 0x4f7e1ad6 ]--------------------------------------------------------------
//           00 01 02 03 04 05 06 07  08 09 0a 0b 0c 0d 0e 0f  01234567 89abcdef
// 00000000  00 00 06 00 00 00 8f bf  06 44 25 06 dd 43 8f bf  ........ .D%..C.. pointer 0x00060000
// 00000010  06 44 96 43 8b 3c 00 00  00 00 01 00 00 00 00 00  .D.C.<.. ........
// 00000020  00 00 00 00 80 3f 00 00  10 40 00 00 10 40 00 00  .....?.. .@...@..
// 00000030  00 3f 00 00 00 3f 00 00  00 3f 00 00 00 00 00 00  .?...?.. .?......
             ^^^^^^^^^^^^^^^^^^^^^^^ this is the data
```

note - Screen to World and World to Screen are 1/2 or 2

**Comment by hectorgimenez** [comment]
@iceisfun thanks for the detailed issue, I would like to discuss a bit more to get better context on this since it's not fully clear to me about the offset we are talking about and the impact. I understand we are reading information from the wrong place (zoomed) instead of normal one? Could you help me understand how this affects the functionality? I'm interested in any ideas you might have for a solution. Looking forward to your input, thanks!

**Comment by hectorgimenez** [comment]
oh, that's super interesting @iceisfun, never thought about that feature but it's true it can be used to increase the precision when hovering, it's a very good tip! 💯

I'm also surprised to see someone else working on something similar in go! I don't see your project in your github profile so I suppose is not open source, you want to connect? I believe we can share some thoughts and maybe collaborate somehow. I'm finding this very interesting. You can reach me via discord: yastxd or just drop me a mail (you can get it from my github profile)
